export const Permissions = {
  DASHBOARD_VIEW: 'dashboard.view',
  PHD_STUDENTS_VIEW: 'phd_students.view',
  PHD_STUDENTS_CREATE: 'phd_students.create',
  PHD_STUDENTS_EDIT: 'phd_students.edit',
  PHD_STUDENTS_DELETE: 'phd_students.delete',
  LECTURERS_VIEW: 'lecturers.view',
  LECTURERS_CREATE: 'lecturers.create',
  LECTURERS_EDIT: 'lecturers.edit',
  LECTURERS_DELETE: 'lecturers.delete',
  DEPARTMENTS_VIEW: 'departments.view',
  DEPARTMENTS_CREATE: 'departments.create',
  DEPARTMENTS_EDIT: 'departments.edit',
  DEPARTMENTS_DELETE: 'departments.delete',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_EDIT: 'roles.edit',
  ROLES_DELETE: 'roles.delete',
} as const;
